### ISSUE TITLE
Content for CCD highlight Video | CCD

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#102]
## Content for CCD highlight Video | CCD
- **Description**: Prepare a content for social media which includes twitter, instagram and Linkedin. 
- **Priority**: High 
- **Due Date**: 21-08-24

## Checklist
- [x] Assign the task to team by @nomadicmehul
- [x] Content done and share with @nomadicmehul for review
- [x] Assign social media team to post

## Additional Notes
#101

**Comment by VedantDomadiya** [comment]
Do we have the highlight Video ready?

**Comment by VedantDomadiya** [comment]
Tracks of all the session will be added in the content

**Comment by nomadicmehul** [comment]
is it done @VedantDomadiya ?

**Comment by VedantDomadiya** [comment]
> is it done @VedantDomadiya ?

Yeah the content is done

**Comment by nomadicmehul** [comment]
@neelshah2409 Please schedule one more post tomorrow evening with this content! Please update the same to social media team.
