### ISSUE TITLE
Content for Podcast's with all speakers | CCD

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#103]
## Content for Podcast's with all speakers | CCD
- **Description**: Prepare a content for social media which includes twitter, instagram and Linkedin. In content include the small information about speakers  and podcast host[@nomadicmehul]. 
- **Priority**: High 
- **Due Date**: 21-08-24

## Checklist
- [x] Assign the task to team by @nomadicmehul
- [x] Content done and share with @nomadicmehul for review
- [x] Assign social media team to post

## Additional Notes
#100

**Comment by nomadicmehul** [comment]
@VedantDomadiya If you want you can create a separate issue for each speakers content, but make sure to link here!

**Comment by VedantDomadiya** [comment]
## General Template for Each Speaker:

### LinkedIn:
```
🎙️ 𝗖𝗮𝘁𝗰𝗵 𝘁𝗵𝗲 𝗟𝗮𝘁𝗲𝘀𝘁 𝗣𝗼𝗱𝗰𝗮𝘀𝘁 𝘄𝗶𝘁𝗵 [𝗦𝗽𝗲𝗮𝗸𝗲𝗿 𝗡𝗮𝗺𝗲]! 🌟

After an inspiring session on [𝗦𝗽𝗲𝗮𝗸𝗲𝗿'𝘀 𝗘𝘃𝗲𝗻𝘁 𝗧𝗼𝗽𝗶𝗰] at the Google Cloud Community Day 2024, we caught up with [𝗦𝗽𝗲𝗮𝗸𝗲𝗿 𝗡𝗮𝗺𝗲] for a quick podcast! 🎤

In this episode, we dive deeper into the insights from the event, explore [𝗦𝗽𝗲𝗮𝗸𝗲𝗿 𝗡𝗮𝗺𝗲]'s thoughts on the future of cloud technology, and get some exclusive behind-the-scenes stories and feedback.

𝘋𝘰𝘯'𝘵 𝘮𝘪𝘴𝘴 𝘰𝘶𝘵 𝘰𝘯 𝘵𝘩𝘪𝘴 𝘦𝘯𝘨𝘢𝘨𝘪𝘯𝘨 𝘤𝘰𝘯𝘷𝘦𝘳𝘴𝘢𝘵𝘪𝘰𝘯—𝘤𝘭𝘪𝘤𝘬 𝘵𝘩𝘦 𝘭𝘪𝘯𝘬 𝘵𝘰 𝘭𝘪𝘴𝘵𝘦𝘯 𝘯𝘰𝘸! 🔗 [Podcast Link]

#GoogleCloudCommunity #CloudInnovation #TechTalks #CCDGN24
```
### X
```
🎙️ New podcast with [Speaker Name] post-Google Cloud Community Day 2024! Dive into their thoughts on [Speaker's Event Topic] and more. Tune in now! 🎧 [Podcast Link] #TechPodcast #CloudComputing #CCDGN24

```

### Instagram:
```
🎧 𝗡𝗲𝘄 𝗣𝗼𝗱𝗰𝗮𝘀𝘁 𝗔𝗹𝗲𝗿𝘁!

We sat down with [Speaker Name] after their session on [Speaker's Event Topic] at Google Cloud Community Day 2024! Get exclusive insights, reviews, and more in our latest podcast episode. 

🔗Check out the full podcast—link in bio!

#Podcast #TechCommunity #GoogleCloud #CCDGN24
```




## For Content
verify the Speaker name and topic 

| **Speaker Name**                                       | **Topic**                                                                  |
|--------------------------------------------------------|---------------------------------------------------------------------------|
| 𝗥𝗶𝗻𝗸𝗲𝘀𝗵 𝗕𝗮𝗻𝘀𝗮𝗹 (Program Director & Master Inventor, IBM) | 𝘊𝘶𝘵𝘵𝘪𝘯𝘨-𝘦𝘥𝘨𝘦 𝘴𝘦𝘤𝘶𝘳𝘪𝘵𝘺 𝘴𝘵𝘳𝘢𝘵𝘦𝘨𝘪𝘦𝘴 𝘧𝘰𝘳 𝘎𝘰𝘰𝘨𝘭𝘦 𝘊𝘭𝘰𝘶𝘥                         |
| 𝗗𝗵𝗮𝗿𝗺𝗲𝘀𝗵 𝗩𝗮𝘆𝗮 (Google Developer Expert - GCP)          | 𝘚𝘤𝘢𝘭𝘪𝘯𝘨 𝘈𝘐 𝘢𝘱𝘱𝘭𝘪𝘤𝘢𝘵𝘪𝘰𝘯𝘴 𝘦𝘧𝘧𝘰𝘳𝘵𝘭𝘦𝘴𝘴𝘭𝘺 𝘸𝘪𝘵𝘩 𝘊𝘭𝘰𝘶𝘥 𝘙𝘶𝘯                       |
| 𝗔𝘀𝗵𝗶𝘀𝗵 𝗧𝗶𝘄𝗮𝗿𝗶 (DevRel Elastic (India))                 | 𝘔𝘶𝘭𝘵𝘪𝘭𝘪𝘯𝘨𝘶𝘢𝘭 𝘙𝘈𝘎 𝘶𝘴𝘪𝘯𝘨 𝘎𝘦𝘮𝘪𝘯𝘪 𝘢𝘯𝘥 𝘌𝘭𝘢𝘴𝘵𝘪𝘤                                 |
| 𝗥𝗮𝗷𝗮𝗻𝗶 𝗘𝗸𝘂𝗻𝗱𝗲☁️                                        | 𝘌𝘹𝘱𝘭𝘰𝘳𝘪𝘯𝘨 𝘵𝘩𝘦 𝘱𝘰𝘸𝘦𝘳 𝘰𝘧 𝘎𝘰𝘰𝘨𝘭𝘦 𝘊𝘭𝘰𝘶𝘥 𝘍𝘶𝘯𝘤𝘵𝘪𝘰𝘯𝘴 𝘧𝘰𝘳 𝘴𝘦𝘳𝘷𝘦𝘳𝘭𝘦𝘴𝘴 𝘢𝘳𝘤𝘩𝘪𝘵𝘦𝘤𝘵𝘶𝘳𝘦𝘴|
| 𝗥𝘂𝗻𝗰𝘆 𝗢𝗼𝗺𝗺𝗲𝗻 (Director, Software Engineering, SonicWall)| 𝘚𝘩𝘢𝘳𝘪𝘯𝘨 𝘴𝘦𝘤𝘶𝘳𝘪𝘵𝘺 𝘱𝘰𝘴𝘵𝘶𝘳𝘦 𝘪𝘮𝘱𝘳𝘰𝘷𝘦𝘮𝘦𝘯𝘵𝘴 𝘧𝘰𝘳 𝘎𝘊𝘗                             |
| 𝗔𝗻𝘂𝗯𝗵𝗮𝘃 𝗦𝗶𝗻𝗴𝗵 (CTO - Dynopii Inc, GDE in ML & GCP)     | 𝘎𝘶𝘪𝘥𝘪𝘯𝘨 𝘵𝘩𝘳𝘰𝘶𝘨𝘩 𝘵𝘩𝘦 𝘳𝘪𝘴𝘦 𝘰𝘧 𝘴𝘦𝘳𝘷𝘦𝘳𝘭𝘦𝘴𝘴 𝘢𝘨𝘦𝘯𝘵𝘴                             |
| 𝗛𝗮𝗿𝘀𝗵 𝗠𝗮𝗻𝘃𝗮𝗿 (Docker Captain, GDE Cloud, CNCF Ambassador)| 𝘜𝘯𝘷𝘦𝘪𝘭𝘪𝘯𝘨 𝘵𝘩𝘦 𝘧𝘶𝘵𝘶𝘳𝘦 𝘰𝘧 𝘞𝘈𝘚𝘔 & 𝘒𝘶𝘣𝘦𝘳𝘯𝘦𝘵𝘦𝘴 𝘧𝘰𝘳 𝘤𝘭𝘰𝘶𝘥-𝘯𝘢𝘵𝘪𝘷𝘦 𝘢𝘱𝘱𝘭𝘪𝘤𝘢𝘵𝘪𝘰𝘯 𝘥𝘦𝘱𝘭𝘰𝘺𝘮𝘦𝘯𝘵 |
| 𝗥𝗶𝘀𝗵𝗶𝗿𝗮𝗷 𝗔𝗰𝗵𝗮𝗿𝘆𝗮 (GDE in ML (Gen AI, Keras), Machine Learning Engineer, Tensorlake) | 𝘉𝘶𝘪𝘭𝘥𝘪𝘯𝘨 𝘮𝘶𝘭𝘵𝘪𝘮𝘰𝘥𝘢𝘭 𝘴𝘦𝘢𝘳𝘤𝘩 𝘸𝘪𝘵𝘩 𝘵𝘩𝘦 𝘎𝘦𝘮𝘪𝘯𝘪 𝘝𝘪𝘴𝘪𝘰𝘯 𝘮𝘰𝘥𝘦𝘭 𝘢𝘯𝘥 𝘙𝘈𝘎           |
| Arun Teja Godavarthi (Developer Community Manager, Google) | General Tech Talk                                                        |
| 𝗠𝗲𝗵𝘂𝗹 𝗣𝗮𝘁𝗲𝗹 (DevRel Consultant, Content creator & Educator - IT) | 𝘎𝘦𝘯𝘦𝘳𝘢𝘭 𝘛𝘦𝘤𝘩 𝘛𝘢𝘭𝘬                                                        |
| 𝗡𝗶𝗿𝗮𝘃 𝗣𝗮𝗰𝗵𝗰𝗵𝗶𝗴𝗮𝗿 (Ecosystem Solution Architect @ IBM)  | Jamming Session                                                          |

**Comment by nomadicmehul** [comment]
Closing this! Thanks @VedantDomadiya 
I am taking care of posting!
