### ISSUE TITLE
Prepare design for CCD highlight Photos

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#106]
## Prepare design for CCD highlight Photos
- **Description**: Prepare highlight photos which cover overall glimpses CCD. Please add the all social media handles as well in poster.
- **Priority**: High 
- **Due Date**: 21-08-24

## Checklist
- [x] Assign the task to team by @nomadicmehul 
- [x] Prepare a PDF file for LinkedIN post 
- [x] Prepare a carousel post for Inshtagram 
- [x] Share with @nomadicmehul for review
- [x] Content

## Additional Notes
@nomadicmehul will select the best 10 photos from event and share here to move with design prepartion.

**Comment by VedantDomadiya** [comment]
All the creatives would have already shared to you by Darshil
