### ISSUE TITLE
Creative for CFS / CFP

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#14]
Need the CFS creative for social media platforms and groups:

CFS link and information: https://github.com/oscfcommunity/GCCD2024/issues/13

**Comment by bharatmk256** [comment]
Image of (2/7/2024)

![Image](https://github.com/oscfcommunity/GCCD2024/assets/37737418/ff8bedeb-70b2-4b65-a2e8-d5a84c6a9cdf)

**Comment by bharatmk256** [comment]
Image of (3/7/2024)


![Image](https://github.com/oscfcommunity/GCCD2024/assets/37737418/82810925-dae1-4c17-b212-3ac80d09d5ef)

**Comment by bharatmk256** [comment]
Image of (4/7/2024)


https://github.com/oscfcommunity/GCCD2024/assets/37737418/796a5d37-913c-4b2f-9b97-29a680bfb8d9

**Comment by nomadicmehul** [comment]
Thank you team! Great work @mpokar  @bharatmk256  🥇
