### ISSUE TITLE
Back up team for Social Media Accounts Owenership

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#22]
- [x] Drop a message in Volunteer group to see if anyone interested. 
- [x] Setup the meeting with interested volunteers

**Comment by nomadicmehul** [comment]
From today, Social media account post ownership given to: 

- LinkedIN : Bikram Sadhukhan
- Twitter : Ronit Gandhi

Roles and Responsibilities: 

1. Post on social accounts 
2. Reply and manage the comments, message

**Comment by neelshah2409** [comment]
Done shared the Twitter access with Ronit !
