### ISSUE TITLE
Unscheduled : Internal Team meeting - CCDGN

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#23]
Meeting scheduled post 10pm based on the availability. 

- [x] Mehul Patel
- [x] Neel Shah
- [x] Mitesh Pokar
- [x] Viral Parmar 
- [x] Pooja Patel 

Bharat Makwana will be on break due to some work commitments!

**Comment by neelshah2409** [comment]
Meeting Key Points:

- Mitesh bhai need to make a list of all the task to be assigned by volunteers
- Mehulbhai visited the venue and confirmed few things : Food and Banner 
- Food Menu confirmation would be given from KU by tomorrow 
- Banner need to be printed by us 
- Viral bhai and Neel would work on the swag part and confirm the items.
