### ISSUE TITLE
MOM Meeting - 13-07-24

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#28]
Link to issue : https://github.com/oscfcommunity/GCCD2024/issues/27

**Comment by neelshah2409** [comment]
List of things discussed in the meet :


GDSC Lead meeting - Neel , Aryan , Kushal, Darshan 
Vendor details of swag and banner
Game booth & Photo Booth 
Community Partners
How we sell more tickets - strategy to be done in doc 
Instagram experiment - Vatsal 
Twitter - Aryan 
Content - Vedant and Krushi
AR Scan Band


Ask to team members
- All the team member do share contact details of vendors for swag and banner printing if you have .
- ⁠Do suggest some good idea for Photo Booth or game booth at event day 
- ⁠Also do share your strategies for selling more ticket and also I would be sharing one document where we can maintain all the points
