### ISSUE TITLE
Creating a Volunteer Handbook and Creating a Gsheet  

### ISSUE THREAD

**Issue by VedantDomadiya** [oscfcommunity/GCCD2024#31]
## Creating a Volunteer Handbook and Creating a Gsheet  
- **Description**: Maintaining a volunteer handbook and creating a google sheet for all the volunteers for assigning the works in the event day.
- **Assignee**: @VedantDomadiya .
- **Priority**: Medium 
- **Due Date**: As early as possible.

## Checklist
- [x] Raw Volunteer handbook
- [x] Raw Google Sheet
- [x] Reviewing with the team
- [x] Final updates

**Comment by VedantDomadiya** [comment]
Below are the Raw files for the Volunteer Handbook
Kindly review it, @nomadicmehul and @neelshah2409 

[CCDGN24_Volunteer-Handbook.docx](https://github.com/user-attachments/files/16216509/CCDGN24_Volunteer-Handbook.docx)
[CCDGN24_Volunteer-Handbook.pdf](https://github.com/user-attachments/files/16216510/CCDGN24_Volunteer-Handbook.pdf)

**Comment by nomadicmehul** [comment]
@VedantDomadiya Looks good but need some information to update so let's sync over google meet and close this. 

You can schedule the call from here: https://cal.com/nomadicmehul/15min

**Comment by VedantDomadiya** [comment]
https://docs.google.com/spreadsheets/d/1HiNwoV1K4MgKRDLCiFQLVQ-peWfFCXeVzBc0P2wa8OU/edit?usp=sharing

Created the raw sheet for the volunteer management.

@nomadicmehul @neelshah2409 Do let me know the structural changes if any , if not, then we maay move ahead by filling the sheet

**Comment by VedantDomadiya** [comment]
updated the Volunteer handbook 
[CCDGN24_Volunteer-Handbook.docx](https://github.com/user-attachments/files/16364029/CCDGN24_Volunteer-Handbook.docx)
[CCDGN24_Volunteer-Handbook.pdf](https://github.com/user-attachments/files/16364031/CCDGN24_Volunteer-Handbook.pdf)

**Comment by VedantDomadiya** [comment]
Updated 
[CCDGN24_Volunteer-Handbook.docx](https://github.com/user-attachments/files/16532770/CCDGN24_Volunteer-Handbook.docx)
[CCDGN24_Volunteer-Handbook.pdf](https://github.com/user-attachments/files/16532771/CCDGN24_Volunteer-Handbook.pdf)

**Comment by nomadicmehul** [comment]
Closing it!
