### ISSUE TITLE
Speaker HandBook

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#33]
## Speaker HandBook
- **Description**: Prepare the speaker handbook with all details from suggestion accommodation, tourist places, venue location from airport and so on.  
- **Assignee**: 
- **Priority**: Medium 
- **Due Date**: 21-07-24

## Checklist
- [x] 3 & 4 starts properties near or centre to venue location 
- [x] Best Places to Visit in Ahmedabad and Gandhinagar 
- [x] Create a "Speaker-handbok.md" file and add the details in markdown format. 
- [x] Create a pdf file for the same

## Additional Notes
Add any additional information or context here.

**Comment by nomadicmehul** [comment]
Place to visit in Ahmedabad
Sarkhej Roza
Bai Harir Ni Vav
Jhulta Minara Sidi Bashir Mosque
Siddi Sayed Mosque
Badshah No Haziro
Rani No Hajiro (Queen's Tomb)
Sabarmati Ashram 
Auto World Vintage Car Museum
Sardar Vallabhbhai Patel National Museum
Calico Museum of Textiles
Tribal Museum
Vikram Sarabhai Space Exhibition Centre
Ahmedabad Heritage Walk
Kankaria Lake
Science City
Thol Bird Santuary 
Nalsarovar bird santuary

Place to visit in Gandhinagar 
adalaj ni vav
Indroda Dinosaur and Fossil Park
Dandi Kutir Museum
Akshardham

Fast food
Go to chandravillas in morning
Das khaman 
Gathiya rath / iscon gathiya 
Manek chok in night
Shakti sandwich 
Karnavati dabeli 
Jaybhavani vadapav
Anjoy frankie 
Raipur bhajiya house 
Ambica daal vada 
Swati snacks 
Puffiza 

authentic Gujarati food
Govardhan thal 
Vishalla 
Rajwadu
MG Agashiye 
Toran dining hall
Urban khichdi (variety of khichdi)
Jasi de parathe (punjabi)
Moti mahal (Non-Veg)

Cafes
Coffe culture 
Varietea 
Mocha 

Sweet 
Ashrafi kulfi 
The chocolate room 
Natural icecrean

@VedantDomadiya Add this in file.

**Comment by VedantDomadiya** [comment]
Created [Speakers-Handbook.md](https://github.com/oscfcommunity/GCCD2024/blob/main/Speakers-Handbook.md)

@nomadicmehul let me know any changes

**Comment by VedantDomadiya** [comment]
Doc and PDF file for the same 

[CCDGN24_Speaker-Handbook.docx](https://github.com/user-attachments/files/16365236/CCDGN24_Speaker-Handbook.docx)
[CCDGN24_Speaker-Handbook.pdf](https://github.com/user-attachments/files/16365238/CCDGN24_Speaker-Handbook.pdf)
