### ISSUE TITLE
Creative for "Ticket discount for community partners" template 

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#37]
## Design for "Ticket discount for community partners"
- **Description**: Create a design to offer a **40% discounts** to our community partners's members. 
- **Ownership**: @mpokar 
- **Priority**: High 
- **Due Date**: 23-07-24

## Checklist
- [x] https://github.com/oscfcommunity/GCCD2024/issues/38
- [x] Share the design file here and upload it in drive link. 
- [x] Share the original design file with community partners. @neelshah2409 
- [ ] The same design can be useful for all other community partners and follow the same process. 

## Additional Notes
Add any additional information or context here.

**Comment by gajjararyan** [comment]
https://docs.google.com/spreadsheets/d/1ZL9UUp5FtEx3QFv0k121kiGl315rLm6EgNwh3cXxJFY/edit?resourcekey=&gid=1172242646#gid=1172242646

@neelshah2409 bhai this is for a community partner are any changes needed?

**Comment by nomadicmehul** [comment]
Closing this!
