### ISSUE TITLE
Speaker Announcement <> Anubhav Singh 

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#42]
🎤 𝐒𝐩𝐞𝐚𝐤𝐞𝐫 𝐒𝐩𝐨𝐭𝐥𝐢𝐠𝐡𝐭: @𝐀𝐧𝐮𝐛𝐡𝐚𝐯 𝐒𝐢𝐧𝐠𝐡 !🌟

Talk Title : The Rise of Serverless Agents: A Beginner's Guide
We are thrilled to welcome Anubhav Singh to the 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐃𝐚𝐲 𝟐𝟎𝟐𝟒 lineup!

• 👨‍💻 Co-founder @Callchimp.ai
• 🧠 Google Developer Expert in ML & GCP
• 🎤 TEDx Speaker
• 📚 Author of 2 Deep Learning Books
• 🔧 Tech Generalist

Anubhav’s extensive knowledge in machine learning, Google Cloud, and entrepreneurship makes him a standout speaker. Get ready to be inspired and gain valuable insights from his diverse experiences.

Don’t miss this incredible opportunity to learn from a true expert!

#CCDGN24 #MachineLearning #GoogleCloud #TEDx #TechGeneralist

📅 𝐌𝐚𝐫𝐤 𝐲𝐨𝐮𝐫 𝐜𝐚𝐥𝐞𝐧𝐝𝐚𝐫𝐬 𝐚𝐧𝐝 𝐬𝐞𝐜𝐮𝐫𝐞 𝐲𝐨𝐮𝐫 𝐭𝐢𝐜𝐤𝐞𝐭𝐬 𝐧𝐨𝐰!
🔗 𝐡𝐭𝐭𝐩𝐬://𝐤𝐨𝐧𝐟𝐡𝐮𝐛.𝐜𝐨𝐦/𝐜𝐜𝐝𝐠𝐧-𝟐𝟎𝟐𝟒

**Comment by neelshah2409** [comment]
Social Handles : 
Linkedin : https://linkedin.com/in/xprilion
Twitter : https://twitter.com/xprilion

**Comment by iamgrepboyy** [comment]
![Anubhav](https://github.com/user-attachments/assets/b9aa97df-5cb8-4413-93fb-8f75deec1fce)

**Comment by VedantDomadiya** [comment]
For X 

```
🎤 Speaker Spotlight: Anubhav Singh 🌟
Talk: The Rise of Serverless Agents: A Beginner's Guide

• Co-founder @Callchimp.ai
• GDE in ML & GCP
• #TEDx Speaker
• Author of 2 DL Books

Join us at #CCDGN24! Save the date and get tickets: https://konfhub.com/ccdgn-2024 #GoogleCloud
```

**Comment by VedantDomadiya** [comment]
For IG

```
🎤 Speaker Spotlight: 𝐀𝐧𝐮𝐛𝐡𝐚𝐯 𝐒𝐢𝐧𝐠𝐡! 🌟

Talk Title: 𝐓𝐡𝐞 𝐑𝐢𝐬𝐞 𝐨𝐟 𝐒𝐞𝐫𝐯𝐞𝐫𝐥𝐞𝐬𝐬 𝐀𝐠𝐞𝐧𝐭𝐬: 𝐀 𝐁𝐞𝐠𝐢𝐧𝐧𝐞𝐫'𝐬 𝐆𝐮𝐢𝐝𝐞

We are thrilled to welcome Anubhav Singh to the Google Cloud Community Day 2024 lineup!

• 👨‍💻 Co-founder @Callchimp.ai
• 🧠 Google Developer Expert in ML & GCP
• 🎤 TEDx Speaker
• 📚 Author of 2 Deep Learning Books
• 🔧 Tech Generalist

Anubhav’s extensive knowledge in machine learning, Google Cloud, and entrepreneurship makes him a standout speaker. Get ready to be inspired and gain valuable insights from his diverse experiences.

Don’t miss this incredible opportunity to learn from a true expert!

#CCDGN24 #MachineLearning #GoogleCloud #TEDx #TechGeneralist

📅 Mark your calendars and secure your tickets now!
🔗 Link in bio
```
