### ISSUE TITLE
Creative for CSA Bangalore + THM Ahmedabad Meetup

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#43]
## Cretive for CSA Bangalore + THM Ahmedabad Meetup
- **Description**:  @nomadicmehul Will be speaking at this meetup and as per discussion decided to provide special discount for this event participants. 
- **Assignee**: Assign the task to a specific team member or volunteer.
- **Priority**: High / Medium / Low
- **Due Date**: Specify the deadline for the task.

## Checklist
- [ ] @neelshah2409 Create a 50% discount code "THM50" on KonfHub. Set the active time line for the same 24 hours only. 
- [x] Standee design of CCD event and highlight 50% discount code "THM50" with QR code. 
- [ ] Prepare the posters as well for the same content for presentation slide. 

## Additional Notes
For more information, you can contact Viral Parmar from TMH.

**Comment by mpokar** [comment]
@nomadicmehul for 3rd point  you can  directly add content  to your presentation slide

**Comment by mpokar** [comment]
[THMEVENT - Standee 3X6.pdf](https://github.com/user-attachments/files/16351923/THMEVENT.-.Standee.3X6.pdf)
Standee file for THM event

**Comment by mpokar** [comment]
[THMEVENT - Standee 3X6-01 1.pdf](https://github.com/user-attachments/files/16352029/THMEVENT.-.Standee.3X6-01.1.pdf)
Standee
