### ISSUE TITLE
Speaker Announcement <> Harsh Manvar 

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#44]
🎤 𝐒𝐩𝐞𝐚𝐤𝐞𝐫 𝐒𝐩𝐨𝐭𝐥𝐢𝐠𝐡𝐭: @𝐇𝐚𝐫𝐬𝐡 𝐌𝐚𝐧𝐯𝐚𝐫 🌟

Talk Title: Exploring the Future: WASM & Kubernetes New Era Cloud-Native Application Deployment

We’re excited to introduce Harsh Manvar as a speaker for 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐃𝐚𝐲 𝟐𝟎𝟐𝟒!

• 🚢 Docker Captain
• 🌐 CNCF Ambassador
• 🔍 K8s Top Answerer on StackOverflow
• 💡 Google Developer Expert

Harsh is a seasoned professional in containerization with a mission to unravel the complexities of WASM and Docker Scout. With years of experience and a wealth of knowledge, his insights will be invaluable for anyone looking to master these technologies.

Don’t miss this opportunity to learn from a true containerization expert!

#CCDGN24 #Containerization #Docker #K8s #CloudExpert

📅 𝐒𝐚𝐯𝐞 𝐭𝐡𝐞 𝐝𝐚𝐭𝐞 𝐚𝐧𝐝 𝐠𝐞𝐭 𝐲𝐨𝐮𝐫 𝐭𝐢𝐜𝐤𝐞𝐭𝐬 𝐧𝐨𝐰!
🔗 𝐡𝐭𝐭𝐩𝐬://𝐤𝐨𝐧𝐟𝐡𝐮𝐛.𝐜𝐨𝐦/𝐜𝐜𝐝𝐠𝐧-𝟐𝟎𝟐𝟒

**Comment by neelshah2409** [comment]
Social Handles: 
Linkedin : https://www.linkedin.com/in/harsh-manvar-64a30aa3/
Twitter : https://twitter.com/manvar_harsh

**Comment by iamgrepboyy** [comment]
![image](https://github.com/user-attachments/assets/7024051b-8670-47c7-952b-aecb538b5619)

**Comment by VedantDomadiya** [comment]
For IG

```
🎤 Speaker Spotlight: 𝐇𝐚𝐫𝐬𝐡 𝐌𝐚𝐧𝐯𝐚𝐫 🌟

Talk Title: 𝐄𝐱𝐩𝐥𝐨𝐫𝐢𝐧𝐠 𝐭𝐡𝐞 𝐅𝐮𝐭𝐮𝐫𝐞: 𝐖𝐀𝐒𝐌 & 𝐊𝐮𝐛𝐞𝐫𝐧𝐞𝐭𝐞𝐬 𝐍𝐞𝐰 𝐄𝐫𝐚 𝐂𝐥𝐨𝐮𝐝-𝐍𝐚𝐭𝐢𝐯𝐞 𝐀𝐩𝐩𝐥𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐃𝐞𝐩𝐥𝐨𝐲𝐦𝐞𝐧𝐭

We’re excited to introduce Harsh Manvar as a speaker for Google Cloud Community Day 2024!

• 🚢 Docker Captain
• 🌐 CNCF Ambassador
• 🔍 K8s Top Answerer on StackOverflow
• 💡 Google Developer Expert

Harsh is a seasoned professional in containerization with a mission to unravel the complexities of WASM and Docker Scout. With years of experience and a wealth of knowledge, his insights will be invaluable for anyone looking to master these technologies.

Don’t miss this opportunity to learn from a true containerization expert!

#CCDGN24 #Containerization #Docker #K8s #CloudExpert

📅 Save the date and get your tickets now!
🔗 Link in bio!


```

**Comment by VedantDomadiya** [comment]
For X

```
🎤 Speaker Spotlight: Harsh Manvar 🌟
Talk: WASM & Kubernetes New Era Cloud-Native Application Deployment

• Docker Captain
• CNCF Ambassador
• K8s Top Answerer
• Google Developer Expert

Join us at #CCDGN24! Save the date and get tickets: https://konfhub.com/ccdgn-2024 #Docker #K8s
```
