### ISSUE TITLE
Speaker Announcement <> Rajni Ekunde

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#45]
🎤 𝐒𝐩𝐞𝐚𝐤𝐞𝐫 𝐒𝐩𝐨𝐭𝐥𝐢𝐠𝐡𝐭: @𝐑𝐚𝐣𝐚𝐧𝐢 𝐄𝐤𝐮𝐧𝐝𝐞 🌟

Talk Title : Harnessing the Power of Google Cloud Functions for Serverless Architectures

We're excited to announce Rajani Ekunde as a speaker for 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐃𝐚𝐲 𝟐𝟎𝟐𝟒!

• 👩‍💻 DevOps Engineer
• 🎓 1x GCP Certified
• 👥 Co-Organizer - WWG Pune
• 📢 Public Speaker
• ✍ Technical Blogger

Rajani is a skilled DevOps Engineer with over 3 years of hands-on experience in various DevOps tools. She specializes in supporting, automating, and optimizing the deployment process using configuration management, CI/CD, and DevOps processes. Her passion for the field extends beyond her job as she enjoys creating POCs and writing DevOps articles on Medium.

Don't miss this opportunity to learn from an industry expert dedicated to staying at the forefront of technology!

#CCDGN24 #DevOps #GoogleCloud #TechLeadership #DevOpsEngineer

📅 𝐒𝐚𝐯𝐞 𝐭𝐡𝐞 𝐝𝐚𝐭𝐞 𝐚𝐧𝐝 𝐠𝐞𝐭 𝐲𝐨𝐮𝐫 𝐭𝐢𝐜𝐤𝐞𝐭𝐬 𝐧𝐨𝐰!
🔗 𝐡𝐭𝐭𝐩𝐬://𝐤𝐨𝐧𝐟𝐡𝐮𝐛.𝐜𝐨𝐦/𝐜𝐜𝐝𝐠𝐧-𝟐𝟎𝟐𝟒

**Comment by neelshah2409** [comment]
Social Handles: 
Linkedin : https://www.linkedin.com/in/rajani103/ 
Twitter : https://twitter.com/misalpavv

**Comment by iamgrepboyy** [comment]
![image](https://github.com/user-attachments/assets/e93840ee-8714-47f0-bb62-2bc854e436c2)

**Comment by VedantDomadiya** [comment]
for IG

```
🎤 Speaker Spotlight: 𝐑𝐚𝐣𝐚𝐧𝐢 𝐄𝐤𝐮𝐧𝐝𝐞 🌟

Talk Title: 𝐇𝐚𝐫𝐧𝐞𝐬𝐬𝐢𝐧𝐠 𝐭𝐡𝐞 𝐏𝐨𝐰𝐞𝐫 𝐨𝐟 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧𝐬 𝐟𝐨𝐫 𝐒𝐞𝐫𝐯𝐞𝐫𝐥𝐞𝐬𝐬 𝐀𝐫𝐜𝐡𝐢𝐭𝐞𝐜𝐭𝐮𝐫𝐞𝐬

We're excited to announce Rajani Ekunde as a speaker for Google Cloud Community Day 2024!

• 👩‍💻 DevOps Engineer
• 🎓 1x GCP Certified
• 👥 Co-Organizer - WWG Pune
• 📢 Public Speaker
• ✍ Technical Blogger

Rajani is a skilled DevOps Engineer with over 3 years of hands-on experience in various DevOps tools. She specializes in supporting, automating, and optimizing the deployment process using configuration management, CI/CD, and DevOps processes. Her passion for the field extends beyond her job as she enjoys creating POCs and writing DevOps articles on Medium.

Don't miss this opportunity to learn from an industry expert dedicated to staying at the forefront of technology!

📅 Save the date and get your tickets now!
🔗 Link in bio!

#CCDGN24 #DevOps #GoogleCloud #TechLeadership #DevOpsEngineer
```

**Comment by VedantDomadiya** [comment]
For X

```
🎤Speaker Spotlight: Rajani Ekunde🌟
Talk: Harnessing the Power of Google Cloud Functions for Serverless Architectures

DevOps Engineer
Co-Organizer WWG Pune
Technical Blogger

Join us at #CCDGN24! Save the date and get tickets: https://konfhub.com/ccdgn-2024

#DevOps #GoogleCloud 
```
