### ISSUE TITLE
Speaker Announcement <> Ashish Tiwari

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#46]
🎤 𝐒𝐩𝐞𝐚𝐤𝐞𝐫 𝐒𝐩𝐨𝐭𝐥𝐢𝐠𝐡𝐭: @𝐀𝐬𝐡𝐢𝐬𝐡 𝐓𝐢𝐰𝐚𝐫𝐢 🌟

Talk Title :  Multilingual RAG using Gemini and Elastic

We're excited to announce Ashish Tiwari as a speaker for 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐃𝐚𝐲 𝟐𝟎𝟐𝟒!

• 👨‍💻 Senior Developer Advocate, India @ Elastic
• 💡 Techpreneur
• 🛠 Community Expert

Ashish Tiwari brings a wealth of experience from the software and email industry. Currently working at Elastic, Ashish has had the opportunity to collaborate with great minds on various stacks, databases, and programming languages. He has worn multiple hats in the startup world, from system design and scaling to coding and customer support.

As an open-source enthusiast and community contributor, Ashish loves to share his tech knowledge and insights. 

Don't miss this chance to learn from an experienced developer advocate passionate about technology and community engagement!

#CCDGN24 #DeveloperAdvocate #TechLeadership #OpenSource

📅 𝐒𝐚𝐯𝐞 𝐭𝐡𝐞 𝐝𝐚𝐭𝐞 𝐚𝐧𝐝 𝐠𝐞𝐭 𝐲𝐨𝐮𝐫 𝐭𝐢𝐜𝐤𝐞𝐭𝐬 𝐧𝐨𝐰!
🔗 𝐡𝐭𝐭𝐩𝐬://𝐤𝐨𝐧𝐟𝐡𝐮𝐛.𝐜𝐨𝐦/𝐜𝐜𝐝𝐠𝐧-𝟐𝟎𝟐𝟒

**Comment by neelshah2409** [comment]
Social Handles: 
Linkedin : https://www.linkedin.com/in/ashishtiwari93/ 
Twitter : https://twitter.com/_ashish_tiwari

**Comment by iamgrepboyy** [comment]
![image](https://github.com/user-attachments/assets/e6413003-2e90-4d21-b534-c3dc6061d143)

**Comment by VedantDomadiya** [comment]
For IG

```
🎤 Speaker Spotlight: 𝐀𝐬𝐡𝐢𝐬𝐡 𝐓𝐢𝐰𝐚𝐫𝐢 🌟
Talk: 𝐌𝐮𝐥𝐭𝐢𝐥𝐢𝐧𝐠𝐮𝐚𝐥 𝐑𝐀𝐆: 𝐔𝐬𝐢𝐧𝐠 𝐆𝐞𝐦𝐦𝐚 𝐟𝐨𝐫 𝐐𝐮𝐞𝐬𝐭𝐢𝐨𝐧𝐢𝐧𝐠 𝐨𝐧 𝐏𝐫𝐢𝐯𝐚𝐭𝐞 𝐃𝐚𝐭𝐚

Meet our #CCDGN24 tech expert:
• Senior Developer Advocate @Elastic
• Techpreneur
• Community Expert
• Open-source enthusiast

Join Ashish for insights on multilingual data & Gemma!

Save the date: 10th Aug, 2024
🔗 Ticket link in bio!
#DeveloperAdvocate #OpenSource #TechLeadership
```

**Comment by VedantDomadiya** [comment]
For X

```
🎤 Speaker Alert: Ashish Tiwari at #CCDGN24!
Talk: Multilingual RAG with Gemma on Private Data

-> Sr. Dev Advocate @elastic
-> Techpreneur
-> Open-source enthusiast

Learn about multilingual data & Gemma!
🎟️ https://konfhub.com/ccdgn-2024
#DeveloperAdvocate #OpenSource
```

**Comment by nomadicmehul** [comment]
Updated the topic name as per Speaker Request: **Updated Title - Multilingual RAG using Gemini and Elastic**
