### ISSUE TITLE
Printing Assists for Event  

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#47]
## Printing Assists for Event  
- **Description**: Preparing the list of printing assets we needed for 10th august event. 
- **Priority**: Medium 
- **Due Date**: 25-07-24

## Checklist
- [x] Banners Size : 10x8
- [x] Side Panels: 16x10 - 2 (left and right)
- [x] Below LED Screen : 19x4
- [x] Screen 3x2
- [x] Podium : 2x4 [ 3 sides ] X 2 ( Because we have 2 podiums ) 
- [x] Registration Desk - 3*2
- [x] Standees : 3x6
- [x] Wristband
- [x] ID Cards and Lanyard
- [ ] Sticker Sheet - A5
- [x] Photo Booth
- [ ] Doodles 

## Additional Notes
Add any additional information or context here.

**Comment by nomadicmehul** [comment]
Venu Partners: https://drive.google.com/drive/folders/1VapMh-uS7buIlhND0HjPCZBIgm5o5c5R?usp=sharing
Sponsors: https://drive.google.com/drive/folders/142XK-y1FkIHIshz_Ak-3HinztuWXEnmH?usp=sharing

**Comment by neelshah2409** [comment]
https://docs.google.com/spreadsheets/d/11Ao09_OMQlm_IHNXkUuZb1yQFYkd8Kf8JEP5_RMchP4/edit?gid=0#gid=0

Sheet

**Comment by nomadicmehul** [comment]
Great work Prashant, @iamgrepboyy @mpokar
