### ISSUE TITLE
Speaker Announcement <>  Runcy Oommen

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#48]
🎤 𝐒𝐩𝐞𝐚𝐤𝐞𝐫 𝐒𝐩𝐨𝐭𝐥𝐢𝐠𝐡𝐭: @𝐑𝐮𝐧𝐜𝐲 𝐎𝐨𝐦𝐦𝐞𝐧 🌟

Talk Title : Security posture improvements for GCP

We're thrilled to announce Runcy Oommen as a speaker for 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐃𝐚𝐲 𝟐𝟎𝟐𝟒!

• 👨‍💻 Multi-Cloud Believer
• 🔒 Technophile & Data Privacy Enthusiast
• 📊 Computer Polyglot & GDE in Cloud

Runcy Oommen is a hands-on software engineer with over 20 years of experience in the software development lifecycle. His expertise lies in the security domain, with key product experience in Cloud Security/Storage, SSL-VPN, Anti-Virus, and Email Security. As a natural perfectionist with an eye for detail, Runcy excels in elevating user experience and identifying product gaps with competitors.

Specialties: C/C++, Go, Python, HTML, Linux, TCP/IP, L4-L7, Network Security, AWS, GCP

Don't miss the chance to learn from a seasoned professional passionate about cloud and security!

#CCDGN24 #CloudSecurity #DataPrivacy #MultiCloud

📅 𝐒𝐚𝐯𝐞 𝐭𝐡𝐞 𝐝𝐚𝐭𝐞 𝐚𝐧𝐝 𝐠𝐞𝐭 𝐲𝐨𝐮𝐫 𝐭𝐢𝐜𝐤𝐞𝐭𝐬 𝐧𝐨𝐰!
🔗 𝐡𝐭𝐭𝐩𝐬://𝐤𝐨𝐧𝐟𝐡𝐮𝐛.𝐜𝐨𝐦/𝐜𝐜𝐝𝐠𝐧-𝟐𝟎𝟐𝟒

**Comment by neelshah2409** [comment]
Social Handles : 
Linkedin : https://www.linkedin.com/in/runcyoommen/ 
Twitter : https://twitter.com/runcyoommen

**Comment by iamgrepboyy** [comment]
![image](https://github.com/user-attachments/assets/c2addeba-87b8-4ba1-8b89-8a7700cfbe17)

**Comment by iamgrepboyy** [comment]
![image](https://github.com/user-attachments/assets/ca8a8b44-b422-4dcb-ad80-455cfd1de05e)

**Comment by VedantDomadiya** [comment]
For IG

```
🎤 Speaker Spotlight: 𝐑𝐮𝐧𝐜𝐲 𝐎𝐨𝐦𝐦𝐞𝐧 🌟
Talk: 𝐒𝐞𝐜𝐮𝐫𝐢𝐭𝐲 𝐩𝐨𝐬𝐭𝐮𝐫𝐞 𝐢𝐦𝐩𝐫𝐨𝐯𝐞𝐦𝐞𝐧𝐭𝐬 𝐟𝐨𝐫 𝐆𝐂𝐏
Meet our #CCDGN24 cloud security expert:

• Multi-Cloud Believer
• Technophile & Data Privacy Enthusiast
• Computer Polyglot & GDE in Cloud

20+ years in software development, specializing in cloud security, storage, and more!

Save the date: 10th Aug, 2024
🔗 Ticket link in bio!
#CloudSecurity #DataPrivacy #MultiCloud
```

**Comment by VedantDomadiya** [comment]
For X

```
🎤 Speaker Alert: Runcy Oommen at #CCDGN24!
Talk: Security posture improvements for GCP

-> Multi-Cloud Expert
-> Data Privacy Enthusiast
-> GDE in Cloud

20+ years in software dev & security
Join us for top #CloudSecurity insights!
🎟️ https://konfhub.com/ccdgn-2024
#MultiCloud
```
