### ISSUE TITLE
Speaker Announcement <> Rishiraj Acharya

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#49]
🎤 𝐒𝐩𝐞𝐚𝐤𝐞𝐫 𝐒𝐩𝐨𝐭𝐥𝐢𝐠𝐡𝐭: @𝐑𝐢𝐬𝐡𝐢𝐫𝐚𝐣 𝐀𝐜𝐡𝐚𝐫𝐲𝐚 🌟

Talk Title : Building Multimodal Search with Gemini Vision model and RAG

We’re thrilled to announce Rishiraj Acharya as a speaker for 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐃𝐚𝐲 𝟐𝟎𝟐𝟒!

• 👨🏻‍🔬 GDE in ML (Gen AI, Keras)
• 🔬 GSoC '22 at TensorFlow
• 🎙️ ML Kolkata Organizer
• 🤗 Hugging Face Fellow
• 🧠 Kaggle Master

Rishiraj Acharya is an engineer who brings innovative ideas from various areas of Machine Learning, including recommendation, ranking, and prediction (RRP), Computer Vision (CV), Natural Language Processing (NLP), speech and audio, Deep learning Networks, Reinforcement Learning, and Distributed Machine Learning. With a versatile skill set, leadership qualities, and enthusiasm to tackle new challenges, Rishiraj is at the forefront of pushing technology forward.

Join us to gain insights from Rishiraj’s extensive expertise and passion for Machine Learning!

#CCDGN24 #MachineLearning #AIExpert #GoogleDevExpert

📅 𝐒𝐚𝐯𝐞 𝐭𝐡𝐞 𝐝𝐚𝐭𝐞 𝐚𝐧𝐝 𝐠𝐞𝐭 𝐲𝐨𝐮𝐫 𝐭𝐢𝐜𝐤𝐞𝐭𝐬 𝐧𝐨𝐰!
🔗 𝐡𝐭𝐭𝐩𝐬://𝐤𝐨𝐧𝐟𝐡𝐮𝐛.𝐜𝐨𝐦/𝐜𝐜𝐝𝐠𝐧-𝟐𝟎𝟐𝟒

**Comment by neelshah2409** [comment]
Social Handles : 
Linkedin : https://linkedin.com/in/rishirajacharya 
Twitter : https://twitter.com/rishirajacharya

**Comment by iamgrepboyy** [comment]
![image](https://github.com/user-attachments/assets/cd2f1c70-f9f1-475f-99e7-bb5920e134b1)

**Comment by VedantDomadiya** [comment]
For IG

```
🎤 Speaker Spotlight: 𝐑𝐢𝐬𝐡𝐢𝐫𝐚𝐣 𝐀𝐜𝐡𝐚𝐫𝐲𝐚 🌟
Talk: 𝐁𝐮𝐢𝐥𝐝𝐢𝐧𝐠 𝐌𝐮𝐥𝐭𝐢𝐦𝐨𝐝𝐚𝐥 𝐒𝐞𝐚𝐫𝐜𝐡 𝐰𝐢𝐭𝐡 𝐆𝐞𝐦𝐢𝐧𝐢 𝐕𝐢𝐬𝐢𝐨𝐧 𝐦𝐨𝐝𝐞𝐥 𝐚𝐧𝐝 𝐑𝐀𝐆

Meet our #CCDGN24 ML expert:
• GDE in ML (Gen AI, Keras)
• GSoC '22 at TensorFlow
• ML Kolkata Organizer
• Hugging Face Fellow
• Kaggle Master

Dive into ML innovations with Rishiraj! From RRP to CV, NLP, and more.

Save the date: 10th Aug, 2024
🔗 Ticket link in bio!

#MachineLearning #AIExpert #GoogleDevExpert
```
