### ISSUE TITLE
Prepare PPT slides for THM Ahmedabad Meetup

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#50]
## Prepare PPT slides for THM Ahmedabad Meetup
- **Description**: Prepare the presentation as per checklist. Please follow official guidelines. 
- **Priority**: Medium 
- **Due Date**: 25-07-24

## Checklist
- [x] Event title ( CCFGN24) 
- [x] Add the agenda 
- [x] Add the all speakers 
- [x] Add venue 
- [x] Community Partners 
- [x] Why you should attend ( Learn from next cloud leaders and experts, Network with peers, meet the professionals to explore opportunities. 
- [x] Discounted Coupon slide

## Additional Notes
#43

**Comment by mpokar** [comment]
Use official guidelines for this PPT. I have attached the guideline link below for you to look over.
https://docs.google.com/presentation/d/1GVvj-S1hToSsienWihPCKjoxMzvvULgbdj5t1EhjtmU/edit?usp=sharing

**Comment by nomadicmehul** [comment]
@VedantDomadiya PPT ready ?
