### ISSUE TITLE
Tshirt Designs for Volunteer 

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#51]
Need some design suggestions for T-shirt  for volnteer

**Comment by K-Khushal** [comment]
https://www.behance.net/search/projects/gdg%20tshirt?tracking_source=typeahead_search_direct

https://www.behance.net/search/projects/gdsc%20tshirt?tracking_source=typeahead_search_direct

**Comment by K-Khushal** [comment]
Any updates on tshirt design ?

**Comment by neelshah2409** [comment]
> Any updates on tshirt design ?

Yes ,it's finalized and also given for printing 😁
