### ISSUE TITLE
Content for Socials 📃

### ISSUE THREAD

**Issue by gajjararyan** [oscfcommunity/GCCD2024#53]
## Task Title
- **Description**: You will receive all social media content here in Doc.
- **Assignee**:  @VedantDomadiya @gajjararyan 
- **Priority**:  Medium  
- **Due Date**: ASAP

Link here :- https://docs.google.com/document/d/1dcW--N7cUYfEploRgseFGv4N3EAFzTnCoFtJEY21d1k/edit?usp=sharing

## Additional Notes
Add any additional information or context here.

**Comment by VedantDomadiya** [comment]
- Remove Rectangular brackets in the link 
- For the Instagram Post : Remove the link and mention "Link in Bio"

Rest is good

**Comment by ronit18** [comment]
- In every content please add the official hashtags(#GoogleCloud, #CloudCommunityDay, #CCDGN24).
- Change #CCDG24 to #CCDGN24.(This is our official hashtags used in all creatives!)

**Comment by gajjararyan** [comment]
> * Remove Rectangular brackets in the link
> * For the Instagram Post : Remove the link and mention "Link in Bio"
> 
> Rest is good

**Comment by gajjararyan** [comment]
You can also edit vedant if there are any small mistakes!

**Comment by ronit18** [comment]
The captions you used are also good like (#WomenInTech #DiversityMatters). We can you use content specific captions. Just make sure that we have our official hashtags also in content.

**Comment by gajjararyan** [comment]
If you have any small changes just add a comment and do it. Is it okay for both?
