### ISSUE TITLE
Sponsor Creative <> Rezoomex | Gold Sponsor

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#56]
## Sponsor Creative for Rezoomex 
- **Description**: Creative for the Rezoomex under Gold sponsor tag. 
- **Priority**: Medium 
- **Due Date**: 28-07-24

## Checklist
- [x] Add the Rezoomex file here 
- [x] Assign the task to creative team lead. @mpokar 
- [x] Submit the creative for review

## Additional Notes
Add any additional information or context here.

**Comment by nomadicmehul** [comment]
Checkout the files: https://drive.google.com/drive/folders/1AEpvPOb5nnW8w5vGRNh1TRMwkc-wgNFG?usp=sharing

Over to you @mpokar

**Comment by nomadicmehul** [comment]
Note for content team: @VedantDomadiya @gajjararyan 

You can tagg the following people, who are travelling to Gandhinagar for this event from the team. 

Anuja Dhopate - [linkedin.com/in/anuja-dhopate-44a1038](https://www.linkedin.com/in/anuja-dhopate-44a1038)
Vinayak Joglekar (Founder/Director) - https://www.linkedin.com/in/vinayak-joglekar-b95329/
Hrishikesh Bidwe - https://www.linkedin.com/in/bhrishikesh/
Susmita Bardhan - https://www.linkedin.com/in/susmitabardhan/
Milind Joshi - https://www.linkedin.com/in/milind-joshi-url/

**Comment by gajjararyan** [comment]
Can you specify which Event, I think I am not aware about this!

**Comment by gajjararyan** [comment]
check this once https://docs.google.com/document/d/1dcW--N7cUYfEploRgseFGv4N3EAFzTnCoFtJEY21d1k/edit#heading=h.s2rh5qe1t6d6  @neelshah2409

**Comment by VedantDomadiya** [comment]
@gajjararyan made small changes and alignments

For Linkedin

```
🌟 𝗘𝘅𝗰𝗶𝘁𝗶𝗻𝗴 𝗦𝗽𝗼𝗻𝘀𝗼𝗿 𝗔𝗻𝗻𝗼𝘂𝗻𝗰𝗲𝗺𝗲𝗻𝘁: 𝗥𝗲𝘇𝗼𝗼𝗺𝗲𝘅 𝗝𝗼𝗶𝗻𝘀 𝗖𝗖𝗗𝗚𝗡𝟮𝟰 𝗮𝘀 𝗚𝗼𝗹𝗱 𝗦𝗽𝗼𝗻𝘀𝗼𝗿! 🌟

We're thrilled to 𝘸𝘦𝘭𝘤𝘰𝘮𝘦 𝙍𝙚𝙯𝙤𝙤𝙢𝙚𝙭 𝙖𝙨 𝙖 𝙂𝙤𝙡𝙙 𝙎𝙥𝙤𝙣𝙨𝙤𝙧 𝘧𝘰𝘳 𝙂𝙤𝙤𝙜𝙡𝙚 𝘾𝙡𝙤𝙪𝙙 𝘾𝙤𝙢𝙢𝙪𝙣𝙞𝙩𝙮 𝘿𝙖𝙮 𝟮𝟬𝟮𝟰 𝙂𝙖𝙣𝙙𝙝𝙞𝙣𝙖𝙜𝙖𝙧!

𝘙𝘦𝘻𝘰𝘰𝘮𝘦𝘹, a pioneer in innovative recruitment solutions, is known for its cutting-edge technology and commitment to transforming the hiring process. Their support plays a crucial role in making our event a success and bringing valuable insights to our community.

𝗠𝗲𝗲𝘁 𝘁𝗵𝗲 𝗥𝗲𝘇𝗼𝗼𝗺𝗲𝘅 𝘁𝗲𝗮𝗺 𝗷𝗼𝗶𝗻𝗶𝗻𝗴 𝘂𝘀:
• Vinayak Joglekar (Founder/Director)
• Anuja Dhopate
• Hrishikesh Bidwe
• Susmita Bardhan
• Milind Joshi

We're excited to have their expertise and innovation at #CCDGN24!

#GoogleCloud #Sponsorship #RecruitmentTech #CloudComputing
```


For Instagram

```
🎉 𝗚𝗼𝗹𝗱 𝗦𝗽𝗼𝗻𝘀𝗼𝗿 𝗔𝗹𝗲𝗿𝘁: 𝗥𝗲𝘇𝗼𝗼𝗺𝗲𝘅 𝗷𝗼𝗶𝗻𝘀 #𝗖𝗖𝗗𝗚𝗡𝟮𝟰! 🚀

We're pumped to have 𝙍𝙚𝙯𝙤𝙤𝙢𝙚𝙭, the recruitment tech innovators, as our 𝙂𝙤𝙡𝙙 𝙎𝙥𝙤𝙣𝙨𝙤𝙧 𝙛𝙤𝙧 𝙂𝙤𝙤𝙜𝙡𝙚 𝘾𝙡𝙤𝙪𝙙 𝘾𝙤𝙢𝙢𝙪𝙣𝙞𝙩𝙮 𝘿𝙖𝙮 2024 𝙂𝙖𝙣𝙙𝙝𝙞𝙣𝙖𝙜𝙖𝙧!

👥 𝗠𝗲𝗲𝘁 𝘁𝗵𝗲𝗶𝗿 𝗮𝘄𝗲𝘀𝗼𝗺𝗲 𝘁𝗲𝗮𝗺 𝗮𝘁 𝘁𝗵𝗲 𝗲𝘃𝗲𝗻𝘁:
• Vinayak Joglekar (Founder/Director)
• Anuja Dhopate
• Hrishikesh Bidwe
• Susmita Bardhan
• Milind Joshi

Rezoomex is transforming hiring with cutting-edge tech. Their support is key to making our event amazing!

𝘙𝘦𝘢𝘥𝘺 𝘵𝘰 𝘯𝘦𝘵𝘸𝘰𝘳𝘬 𝘸𝘪𝘵𝘩 𝘵𝘩𝘦 𝘣𝘦𝘴𝘵? 𝘚𝘦𝘦 𝘺𝘰𝘶 𝘵𝘩𝘦𝘳𝘦! 💼✨

#GoogleCloud #TechEvent #RecruitmentInnovation #CloudComputing
```

for X

```
🌟 Announcing our Gold Sponsor: Rezoomex! 🌟
Thrilled to have this recruitment tech pioneer supporting #CCDGN24!

Meet their team:
Vinayak Joglekar
Anuja Dhopate
Hrishikesh Bidwe
Susmita Bardhan
Milind Joshi

Their innovative solutions are reshaping hiring. Join us to learn more!
```
