### ISSUE TITLE
Keynote Speaker Announcement <>  Rinkesh Bansal

### ISSUE THREAD

**Issue by neelshah2409** [oscfcommunity/GCCD2024#60]
🎤 **Keynote** 𝐒𝐩𝐞𝐚𝐤𝐞𝐫 𝐒𝐩𝐨𝐭𝐥𝐢𝐠𝐡𝐭:  @ Rinkesh Bansal🌟

We're excited to announce **Rinkesh Bansal** as a  keynote speaker for 𝐆𝐨𝐨𝐠𝐥𝐞 𝐂𝐥𝐨𝐮𝐝 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐃𝐚𝐲 𝟐𝟎𝟐𝟒!

 - 👨‍💻Program Director & Master Inventor@ IBM
 - 🔒 Leader of the Security Dev Lab at IBM, Ahmedabad
 -  🎓 He has 14 + patents on his name
 -  🏆 Dynamic speaker in International Conferences 

Rinkesh  brings a wealth of knowledge in cloud security . He has more than two decades of extensive experience in team management and product development. His passion for mentoring and played a pivotal role in establishing a new Security Development division in Ahmedabad, which now comprises ~200 skilled security professionals.

Don't miss this opportunity to learn from one of the best in the field!

#CCDGN24 #Security #keynotespeaker

📅 𝐒𝐚𝐯𝐞 𝐭𝐡𝐞 𝐝𝐚𝐭𝐞 𝐚𝐧𝐝 𝐠𝐞𝐭 𝐲𝐨𝐮𝐫 𝐭𝐢𝐜𝐤𝐞𝐭𝐬 𝐧𝐨𝐰!
🔗 https://konfhub.com/ccdgn-2024

**Comment by neelshah2409** [comment]
Linkedin :  https://www.linkedin.com/in/rinkesh-bansal-09798843/

**Comment by mpokar** [comment]
![Rinkesh Bansal](https://github.com/user-attachments/assets/1991aafd-29e0-4c4c-a33f-e2315c1661b1)

**Comment by mpokar** [comment]
![Uploading Rinkesh Bansal (1).png…]()

**Comment by mpokar** [comment]
![Rinkesh Bansal (1)](https://github.com/user-attachments/assets/7bf6ecf8-a541-462d-aab8-85cfae87db1a)
