### ISSUE TITLE
GCCDN24 Intro video 

### ISSUE THREAD

**Issue by gajjarvatsall** [oscfcommunity/GCCD2024#62]
## Task Title
- **Description**: Creating a 1 minute intro video for the GCCDN24
- **Assignee**: Vatsal Gajjar
- **Priority**: High
- **Due Date**: 1 Aug,24

**Video Link** :- https://drive.google.com/file/d/15MT84SudqYbZ64Ky8KLkkfOWtZWI9lqO/view?usp=sharing

## Additional Notes
Add any additional information or context here.

**Comment by nomadicmehul** [comment]
Great work @gajjarvatsall :)
