### ISSUE TITLE
Update the Sponsors and Community Partners | Main Repo

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#65]
## Update the Sponsors and Community Partners | Main Repo
- **Description**: Update the sponsor and community partner information in main readme.md file. 
- **Assignees**: @VedantDomadiya 
- **Priority**: Medium 
- **Due Date**: 04-07-24

## Checklist
- [x] Update : https://github.com/oscfcommunity/GCCD2024/blob/main/SPONSORS.md
- [x] Update: https://github.com/oscfcommunity/GCCD2024/blob/main/COMMUNITY_PARTNERS.md

## Additional Notes
You will get the sponsor and community partners information from @neelshah2409

**Comment by VedantDomadiya** [comment]
Updated both pages 
I'll update the logos in Community partners once i have the access

@nomadicmehul kindly review the structure of the pages

**Comment by VedantDomadiya** [comment]
I added the logos given in community partners

**Comment by nomadicmehul** [comment]
Closing this!
