### ISSUE TITLE
Speaker Video Byte | Session promotion | Reel 

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#66]
## Speaker Video Byte | Session promotion 
- **Description**: We have already got a speaker byte so edit the clips in CCD theme or just add the logo for the event. Add the QR code or event registration link at the end. 
- **Assignee**:  @mpokar 
- **Priority**: High / Medium / Low
- **Due Date**: Specify the deadline for the task.

## Checklist
- [x] Edit the video - Clear the voice and noise reduction if any, colour correction. 
- [x] Create a thumbnail for the instagram 

## Additional Notes
Speaker bytes: https://drive.google.com/drive/folders/1WTyIk_9I5OKxhCgoAvqDUDxq3D4vQy-8?usp=sharing

**Comment by nomadicmehul** [comment]
@meetraval0908 assigning this to you as per discussion with @neelshah2409

**Comment by gajjararyan** [comment]
https://drive.google.com/drive/folders/18q0Do1UrhChnJT18rY-ckHAI-1q04p_1?usp=sharing Videos for Speakers to post

**Comment by gajjarvatsall** [comment]
Speakers reel with their thumbnails

link :- https://drive.google.com/drive/folders/16UYkCZzcybPYWTosVBjV36fnsnQ_mNVL?usp=sharing

**Comment by nomadicmehul** [comment]
Great work @gajjarvatsall @gajjararyan
