### ISSUE TITLE
Flash sale promotion | CCDGN24 | Creative 

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#67]
## Flash sale promotion | CCDGN24 | Creative 
- **Description**: Create a Flash sale promotion design for the social media campgain. 
- **Assignee**: @mpokar  @neelshah2409 
- **Priority**: High 
- **Due Date**: 04-07-24

## Checklist
- [ ] Create a design fir flash sale with 55% discount 
- [ ] @neelshah2409 Create a coupon code for the 1 hour on the 06-07-24 on 07.00pm - 09.00pm
- [ ] Post should go live on social media on 05-07-24

## Additional Notes
Add any additional information or context here.

**Comment by VedantDomadiya** [comment]
For Content : https://github.com/oscfcommunity/GCCD2024/issues/76
