### ISSUE TITLE
Content for Social Post (Speaker's byte video)

### ISSUE THREAD

**Issue by gajjarvatsall** [oscfcommunity/GCCD2024#71]
## Task Title
- **Description**: Write a content for speaker's byte video for social media
- **Assignee**: @VedantDomadiya @aryangajjar
- **Priority**: High 
- **Due Date**: 5 August,2024
- **linked issues** : https://github.com/oscfcommunity/GCCD2024/issues/66

**Comment by VedantDomadiya** [comment]
### Speaker Byte Video Content
- Ashish Tiwari : https://github.com/oscfcommunity/GCCD2024/issues/72
- Rishiraj Acharya : https://github.com/oscfcommunity/GCCD2024/issues/73
- Rajani Ekunde : https://github.com/oscfcommunity/GCCD2024/issues/74
- Harsh Manvar : https://github.com/oscfcommunity/GCCD2024/issues/75
