### ISSUE TITLE
Finalised the Food Menu

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#9]

**Comment by neelshah2409** [comment]
Breakfast | Poha
-- | --
  | Tea /Coffee
  |  
Lunch | Salad
  | Paneer Sabji
  | Veg Sabji
  | Dal Makhni
  | Rice
  | Chaas
  | Sweet
  | Papad & achar
  |  
  |  
Hi Tea | Tea/Coffee
  | Cookies


</body>
</html>

**Comment by nomadicmehul** [comment]
Sent this information to Food Vendor to get the final quotation.
