### ISSUE TITLE
Prepare Post event reports - #CCDGN24

### ISSUE THREAD

**Issue by nomadicmehul** [oscfcommunity/GCCD2024#97]
## Prepare Post event reports - #CCDGN24
- **Description**: Reports includes our overall achievements from this event.  
- **Priority**: High 
- **Due Date**: 17-08-24

## Checklist
- [x] Prepare the draft
- [x] Review by @nomadicmehul 
- [x] Publish the reports

## Additional Notes
Required multiple meetings, @VedantDomadiya feel free to ping me to close this!

**Comment by VedantDomadiya** [comment]
---

## **Google Cloud Community Day 2024: Post-Event Report**

### **Event Highlights**

On August 10, 2024, we hosted an unforgettable Google Cloud Community Day at Karnavati University, bringing together over 600+ attendees, 10 inspiring speakers, and a fantastic team of volunteers. We were thrilled to see that 48% of our attendees were professionals, showcasing the diverse range of individuals interested in cloud technology!

### **Speakers and Topics**

We were honored to have a lineup of distinguished speakers who shared their expertise on various topics:

1. **Rinkesh Bansal** (Program Director & Master Inventor, IBM)  
   *Topic:* Cutting-edge security strategies for Google Cloud

2. **Dharmesh Vaya** (Google Developer Expert - GCP)  
   *Topic:* Scaling AI applications effortlessly with Cloud Run

3. **Ashish Tiwari** (DevRel Elastic (India))  
   *Topic:* Multilingual RAG using Gemini and Elastic

4. **Rajani Ekunde**  
   *Topic:* Exploring the power of Google Cloud Functions for serverless architectures

5. **Runcy Oommen** (Director, Software Engineering, SonicWall)  
   *Topic:* Sharing security posture improvements for GCP

6. **Anubhav Singh** (CTO - Dynopii Inc, Google Developer Expert in ML & GCP)  
   *Topic:* Guiding through the rise of serverless agents

7. **Harsh Manvar** (Docker Captain, GDE Cloud, CNCF Ambassador)  
   *Topic:* Unveiling the future of WASM & Kubernetes for cloud-native application deployment

8. **Rishiraj Acharya** (GDE in ML (Gen AI, Keras), Machine Learning Engineer, Tensorlake)  
   *Topic:* Building multimodal search with the Gemini Vision model and RAG

9. **Arun Teja Godavarthi** (Developer Community Manager, India Developer Ecosystem, Google)  
   *Topic:* General Tech Talk

10. **Mehul Patel** (DevRel Consultant, Content creator & Educator - IT)  
    *Topic:* General Tech Talk

### **Event Activities**

We spiced up the event with some fantastic activities:

- **Jamming Session by Nirav Pachchigar** (Ecosystem Solution Architect @ IBM): A musical interlude that had everyone tapping their feet.
- **Poetry by Suhani Soni:** A heartfelt poetry recital that captivated the audience.
- **"Life is Unfair" Game:** A fun and interactive game led by our enthusiastic volunteers.
- **Fun Activity by Host:** Engaging and entertaining activities throughout the event by our professional host, **Drijesh Patel** from IBM.

### **Social Media Impact**

The event generated incredible buzz on social media:

- **Social Media Impressions:** Thousands of impressions across various platforms, showcasing the event's reach and engagement.
- **Tags Received:** We received a great number of tags from attendees, highlighting their experiences and takeaways.

### **Feedback and Testimonials**

We received overwhelming positive feedback from both attendees and speakers:

- **Attendee Feedback:**
  ![Attendee Feedback Photo 1](#)
  ![Attendee Feedback Photo 2](#)

- **Speaker Quotes:**
  - "This event was a fantastic opportunity to connect with the community and share insights. The engagement and enthusiasm of the attendees were inspiring!" - **Rinkesh Bansal**
  - "It's always a pleasure to discuss the latest in cloud technology with such a passionate audience. Kudos to the organizers for putting together a great event!" - **Dharmesh Vaya**

### **Acknowledgments**

A big thank you to our sponsor **Rezoomex** for supporting this event. We also want to extend our gratitude to our community partners and the amazing community leaders who volunteered and contributed to the success of the event.

### **Cool Fact!**

Did you know? All activities and tasks for organizing and managing #CCDGN24 were completely managed on GitHub! From poster creation to content generation for this report, everything was done on GitHub. This allows all contributors to share their work and provides a blueprint for future organizers. Feel free to clone our repo to organize your event!

### **Links to Sessions and Podcasts**

- **Speaker Sessions:** [Link to Sessions](#)
- **Speaker Podcasts:** [Podcast Links](#)
- **Linktree for Social Media:** [Linktree](#)

Thank you to everyone who made Google Cloud Community Day 2024 a resounding success! We look forward to seeing you next year!

---

**Comment by VedantDomadiya** [comment]
---

## **Google Cloud Community Day 2024: Post-Event Report**

### **Event Highlights**

![Group Photo](#)

On August 10, 2024, we hosted an unforgettable Google Cloud Community Day at Karnavati University, bringing together over 600+ attendees, 10 inspiring speakers, and a fantastic team of volunteers. We were thrilled to see that 48% of our attendees were professionals, showcasing the diverse range of individuals interested in cloud technology!

![Attendee Ratio Pie Chart](#)  
*Pie Chart showing the ratio of Students to Professionals present at the event.*

### **Speakers and Topics**

For details about our incredible speakers and their topics, please refer to the [Speaker Presentation](#) (PPT file) which includes all their images and a welcome slide.

### **Event Activities**

We spiced up the event with some fantastic activities:

- **Jamming Session by Nirav Pachchigar** (Ecosystem Solution Architect @ IBM): A musical interlude that had everyone tapping their feet.
- **Poetry by Suhani Soni:** A heartfelt poetry recital that captivated the audience.
- **"Life is Unfair" Game:** A fun and interactive game led by our enthusiastic volunteers.
- **Fun Activity by Host:** Engaging and entertaining activities throughout the event by our professional host, **Drijesh Patel** from IBM.

### **Social Media Impact**

The event generated incredible buzz on social media:

- **Social Media Impressions:** Thousands of impressions across various platforms, showcasing the event's reach and engagement.
- **Tags Received:** We received a great number of tags from attendees, highlighting their experiences and takeaways.

### **Feedback and Testimonials**

#### **Speaker Spotlight**

| Speaker           | Designation                                          | Podcast Link                                       |
|-------------------|------------------------------------------------------|----------------------------------------------------|
| Rinkesh Bansal    | Program Director & Master Inventor, IBM              | [Podcast](#)                                       |
| Dharmesh Vaya     | Google Developer Expert - GCP                        | [Podcast](#)                                       |
| Ashish Tiwari     | DevRel Elastic (India)                               | [Podcast](#)                                       |
| Rajani Ekunde     | DevOps Engineer                                      | [Podcast](#)                                       |
| Runcy Oommen      | Director, Software Engineering, SonicWall            | [Podcast](#)                                       |
| Anubhav Singh     | CTO - Dynopii Inc, Google Developer Expert in ML & GCP| [Podcast](#)                                       |
| Harsh Manvar      | Docker Captain, GDE Cloud, CNCF Ambassador           | [Podcast](#)                                       |
| Rishiraj Acharya  | GDE in ML (Gen AI, Keras), Machine Learning Engineer, Tensorlake | [Podcast](#)                            |
| Arun Teja Godavarthi | Developer Community Manager, India Developer Ecosystem, Google | [Podcast](#)                         |
| Mehul Patel       | DevRel Consultant, Content Creator & Educator - IT   | [Podcast](#)                                       |

### **Acknowledgments**

![Companies Associated](#)

A big thank you to our sponsors and partners:

- **Google Developer Groups (GDG)**
- **Rezoomex**
- **Karnavati University** - Venue Partner

We also want to extend our gratitude to our community partners and the amazing community leaders who volunteered and contributed to the success of the event.

### **Cool Facts!**

- **GitHub Management:** All activities and tasks for organizing #CCDGN24 were managed on GitHub. From poster creation to content generation for this report, everything was done using GitHub. Check out our [Completed Issues](#) for a behind-the-scenes look!
- **Professional Involvement:** All our speakers, host, artists/performers, and most volunteers were professionals, ensuring a high-quality experience for all attendees.
- **Our Host:** Drijesh Patel, our energetic host, is a Program Manager at IBM and brought his unique blend of professionalism and charisma to the event.

### **Community Partners**

![Community Partners](#)

### **Links to Sessions and Podcasts**

- **Speaker Sessions:** [Link to Sessions](#)
- **Speaker Podcasts:** [Podcast Links](#)
- **Linktree for Social Media:** [Linktree](#)

Thank you to everyone who made Google Cloud Community Day 2024 a resounding success! We look forward to seeing you next year!

---

**Comment by nomadicmehul** [comment]
Thanks @VedantDomadiya Great work man!
